#!/bin/bash
docker-on-x run --rm \
	-it \
	--name intellij \
	-v $HOME/intellijSettings/intellij:/home/developer/.IntelliJIdea2019.2 \
	-v $HOME/intellijSettings/java:/home/developer/.java \
	-v $HOME/code:/home/developer/IdeaProjects \
	-v $HOME/.m2:/home/developer/.m2 \
	intellij
