#!/bin/bash
docker run -it --rm \
        -v /home/fibe/code:/home/developer/code \
        -v /home/fibe/code/github/docker-stuff/devenv/nvim:/home/developer/.config/nvim \
        --name devenv \
        devenv
