FROM archlinux:base-devel

ENV USERNAME developer
ENV BUILD build

ARG DOCKER_GID=3000

RUN groupadd -g $DOCKER_GID docker

RUN pacman -Syyu --noconfirm \
	&& pacman -S --noconfirm \
        mlocate tar \
        sudo openssh zsh grml-zsh-config docker git nodejs npm python python-pip neovim \
        jre-openjdk jdk-openjdk java-openjfx \
        jad maven


RUN cd /tmp \
    && curl -X GET 'https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz' --output jdk15.0.2.tar.gz \
    && tar xzf jdk15.0.2.tar.gz \
    && mv jdk-15.0.2 /usr/lib/jvm/java-15-openjdk

RUN useradd --shell=/bin/zsh $BUILD
RUN usermod -L $BUILD
RUN echo "$BUILD ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER $BUILD


RUN mkdir /tmp/aur \
	&& cd /tmp/aur \
    && curl -X GET 'https://aur.archlinux.org/cgit/aur.git/snapshot/nerd-fonts-complete.tar.gz' --output fonts.tar.gz \
    && tar xzf fonts.tar.gz \
    && cd nerd-fonts-complete \
	&& makepkg -sic --noconfirm

USER root

RUN userdel -r $BUILD && rm -rf /home/$BUILD
RUN sed -i "/${BUILD} ALL=(ALL) NOPASSWD: ALL/d" /etc/sudoers

RUN pacman -Scc --noconfirm
RUN rm -rf /tmp/*

RUN echo "%wheel ALL=(ALL) ALL" >> /etc/sudoers
RUN useradd -m -G wheel,docker -s /bin/zsh $USERNAME \
	&& echo "$USERNAME:$USERNAME" | chpasswd

RUN dbus-uuidgen --ensure=/etc/machine-id

RUN archlinux-java set java-16-openjdk

USER developer
WORKDIR /home/$USERNAME
COPY . .

RUN nvim --headless -c 'autocmd User PackerComplete sleep 20 | quitall' -c 'silent PackerCompile'
#RUN nvim --headless -c 'autocmd User PackerComplete | quitall'
#RUN nvim --headless -c 'silent PackerSync'
#
#RUN nvim --headless \
#        +"sleep 10" \
#        +"silent TSInstall python bash java json" \
#        +"sleep 60" \
#        +"silent LspInstall python" \
#        +"silent LspInstall bash" \
#        +"silent LspInstall java" \
#        +"silent LspInstall json" \
#        +"sleep 120" +qa

WORKDIR /home/$USERNAME

ENTRYPOINT ["/bin/zsh"]
