#!/bin/bash
docker-on-x run --rm \
    -it \
    --name vscode \
    -v $HOME/:/home/developer/ \
    -v $HOME/.m2:/home/developer/.m2 \
    -v $HOME/vscode/:/home/developer/.cache \
    -v $HOME/vscode/config/:/home/developer/.config \
    -v $HOME/vscode/oss:/home/developer/.vscode-oss \
    -v /dev/shm:/dev/shm \
    --device /dev/dri \
    --security-opt seccomp=/etc/docker/seccomp/default2.json \
    --memory 4g \
    qwelyt/apps:VSCode "$@"
#    --user "$(id -u):$(id -g)" \
