#!/bin/bash
NAME=${@// /_}
NAME=${NAME////_}
docker-on-x run --rm \
    -it \
    --name cadquery-$NAME \
    -e TZ=Europe/Stockholm \
    -e GDK_SCALE \
    -e GDK_DPI_SCALE \
    -v $HOME/.cadquery:/root/.config/ \
    -v /etc/localtime:/etc/localtime:ro \
    -v "$PWD":/files/ \
    --device /dev/snd \
    --device /dev/dri \
    --device /dev/bus/usb \
    --group-add audio \
    --group-add video \
    qwelyt/apps:cq-editor-jern $@
