name: checkout_and_login

on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  checkoutAndLogin:
      name: Checkout and Login
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
