name: CI

on:
  workflow_dispatch:
    inputs:
      app:
        description: The app to build
        type: string
        required: true

env:
 REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}

jobs:
  OpenSCAD:
    name: Build OpenSCAD container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 
      
      - run: echo $GITHUB_SHA
      - run: echo ${{ github.sha }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: OpenSCAD/
          push: true
          tags: qwelyt/apps:openscad , qwelyt/apps:openscad-${{ github.sha }}
#      - name: Build and publish
#        run: |
#          cd OpenSCAD
#          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}"
#          docker build . --file Dockerfile --tag ${{ env.REPO }}:openscad-$GITHUB_SHA
#          docker push ${{ env.REPO }}:openscad-$GITHUB_SHA
