name: CI

on:
  workflow_dispatch:

env:
 REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}

jobs:
  OpenSCAD:
    name: Build OpenSCAD container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3
      
      - name: Build and publish
        run: |
          cd OpenSCAD
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}"
          docker build . --file Dockerfile --tag ${{ env.REPO }}:openscad-$GITHUB_SHA
          docker push ${{ env.REPO }}:openscad-$GITHUB_SHA
