name: CI

on:
  workflow_dispatch:
    inputs:
      app:
        description: The app to build
        required: true
        type: choice
        options:
          - OpenSCAD
          - CQ-Editor
          - Firefox

env:
 REPO: qwelyt/apps
 OS: ubuntu-latest

jobs:
  OpenSCAD:
    if: ${{ github.event.inputs.app == 'OpenSCAD' }}
    name: Build OpenScad container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: OpenSCAD/
          push: true
          tags: ${{ env.REPO }}:openscad , ${{ env.REPO }}:openscad-${{ github.sha }}
