#!/bin/bash
NAME=${@// /_}
NAME=${NAME////_}
#   --user=$UID:1000 \
#    -v $HOME/code/github/cadquery/cadquery:/opt/miniconda3/pkgs/cadquery-master-py3.9/lib/python3.9/site-packages/cadquery \
#    -v $HOME/code/github/cadquery/cadquery:/opt/miniconda3/lib/python3.9/site-packages/cadquery \
docker-on-x run --rm \
    -it \
    --name cadquery-$NAME \
    -e TZ=Europe/Stockholm \
    -e GDK_SCALE \
    -e GDK_DPI_SCALE \
    -v $HOME/.cadquery:/root/.config/ \
    -v /etc/localtime:/etc/localtime:ro \
    -v "$PWD":/files/ \
    --device /dev/snd \
    --device /dev/dri \
    --device /dev/bus/usb \
    --group-add audio \
    --group-add video \
    cadquery $@
